### PR TITLE
Update contrib libs to 2012 locations

### PR DESCRIPTION
**Pull request by gioele**
This changes updates the paths of the needed external libraries to their current locations.

### CODE REVIEW

**Comment by FranklinChen** [comment]
Is this tool being maintained any longer? I was looking for XML diff libraries and found this one but it seems to have been abandoned.

**Comment by ept** [comment]
Sorry, I don't have time to maintain this. I just took the code from the University of Helsinki research project, and refactored it a bit. I don't think it's in a usable state, I'm afraid.

**Comment by FranklinChen** [comment]
OK. Can you just merge this pull request, then I'll see if I can make use of this project and maybe keep it going if it is useful to me?

**Comment by ept** [comment]
Sure, would be awesome if you want to take it over!

**Pull request merged**
